# Generated by Django 5.0.7 on 2024-07-20 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('seo_meta_title', models.CharField(max_length=100)),
                ('seo_meta_keywords', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('is_reply', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('image', models.CharField(max_length=100)),
                ('seo_meta_title', models.CharField(max_length=100)),
                ('seo_meta_description', models.CharField(max_length=100)),
                ('seo_meta_keywords', models.CharField(max_length=100)),
                ('is_visibility', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guard_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_timezone', models.CharField(max_length=100)),
                ('site_logo', models.CharField(max_length=100)),
                ('site_favicon', models.CharField(max_length=100)),
                ('site_name', models.CharField(max_length=100)),
                ('site_description', models.TextField()),
                ('site_keywords', models.TextField()),
                ('site_meta_title', models.CharField(max_length=100)),
                ('site_meta_description', models.CharField(max_length=100)),
                ('site_meta_keywords', models.CharField(max_length=100)),
                ('site_meta_author', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('company_logo', models.CharField(max_length=100)),
                ('email_setting_driver', models.TextField()),
                ('email_setting_host', models.CharField(max_length=100)),
                ('email_setting_port', models.CharField(max_length=100)),
                ('email_setting_encryption', models.CharField(max_length=100)),
                ('email_setting_username', models.CharField(max_length=100)),
                ('email_setting_password', models.CharField(max_length=100)),
                ('seo_setting_title', models.CharField(max_length=100)),
                ('seo_setting_description', models.CharField(max_length=100)),
                ('seo_setting_keywords', models.CharField(max_length=100)),
                ('seo_setting_author', models.CharField(max_length=100)),
                ('seo_setting_image', models.CharField(max_length=100)),
                ('google_analytics_id', models.CharField(max_length=100)),
                ('google_analytics_script', models.TextField()),
                ('google_analytics_enable', models.BooleanField(default=True)),
                ('recaptcha_key', models.CharField(max_length=100)),
                ('recaptcha_secret', models.CharField(max_length=100)),
                ('recaptcha_enable', models.BooleanField(default=True)),
                ('social_facebook', models.CharField(max_length=100)),
                ('social_twitter', models.CharField(max_length=100)),
                ('social_instagram', models.CharField(max_length=100)),
                ('social_youtube', models.CharField(max_length=100)),
                ('social_linkedin', models.CharField(max_length=100)),
                ('social_pinterest', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleHasPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('images', models.TextField()),
                ('seo_meta_title', models.CharField(max_length=100)),
                ('seo_meta_keywords', models.CharField(max_length=100)),
                ('seo_meta_description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
