# Generated by Django 5.0.7 on 2024-07-20 03:42

from django.db import migrations

def create_data(apps, schema_editor):
    Status = apps.get_model('api', 'Status')
    Status(name='completed', slug='completed').save()
    Status(name='coming Soon', slug='coming-soon').save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
