# Generated by Django 5.0.7 on 2024-07-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_token_created_at_alter_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
