# Generated by Django 5.0.7 on 2024-07-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_category_image_alter_page_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
