# Generated by Django 5.0.7 on 2024-07-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_setting_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
